using EgyptTax.Application.Pdf;
using EgyptTax.Application.Verification;
using EgyptTax.Domain.Invoices;
using EgyptTax.Domain.MasterData;
using EgyptTax.Domain.Workflow;
using EgyptTax.Infrastructure.Pdf;
using EgyptTax.Infrastructure.Verification;
using EgyptTax.SharedKernel;
using UglyToad.PdfPig;
using UglyToad.PdfPig.Content;

namespace EgyptTax.ContractTests.Pdf;

/// <summary>
/// T079 — every PDF generated by the renderer MUST contain every
/// legally required field per
/// <c>contracts/legal-invoice-fields.md</c> per SC-008. The contract
/// asserts presence by extracting text from the rendered PDF (via
/// <c>UglyToad.PdfPig</c>) and asserting substring presence for the
/// English-side fields, plus image-presence checks for the FR-044
/// QR seal.
///
/// Scope notes (deferred from MVP):
///  * Credit-note specifics (section G of the contract) — the
///    CreditNote document type doesn't exist in the domain yet;
///    that test lands when the entity does.
///  * The contract calls for ≥ 100 random invoices — we run one
///    fixture per customer-tax-profile bucket here (3 invoices) so
///    the per-bucket discriminator paths are exercised; a property-
///    style scaling test can land alongside the dashboard perf work.
///  * Strict Arabic-text extraction is font-dependent and excluded
///    from substring assertions; English / numeric strings are the
///    locale-neutral acceptance bar.
/// </summary>
[Collection(PdfRenderingCollection.Name)]
public class InvoicePdfFieldsTests
{
    private readonly QuestPdfInvoiceRenderer _renderer = new();

    [Fact]
    public void Every_Required_Field_Present_On_B2BRegistered_Invoice()
    {
        var fixture = NewFixture(CustomerTaxProfileType.B2BRegistered);
        var pdf = _renderer.Render(fixture.Request);

        var (text, imageCount) = ReadPdf(pdf);

        text.Should()
            .Contain("Tax Invoice", because: "section A — document type label MUST be present");
        text.Should()
            .Contain(
                fixture.Invoice.DocumentNumber!,
                because: "section A — canonical document number MUST appear"
            );
        text.Should()
            .Contain(fixture.Issuer.LegalName.English, because: "section B — issuer legal name");
        text.Should()
            .Contain(
                fixture.Issuer.TaxRegistrationNumber,
                because: "section B — issuer TIN MUST appear"
            );
        text.Should()
            .Contain(
                fixture.Issuer.CommercialRegistrationNumber,
                because: "section B — commercial registration number"
            );
        text.Should().Contain(fixture.Receiver.Name.English, because: "section C — customer name");
        text.Should()
            .Contain(
                fixture.Invoice.CustomerTaxProfileSnapshot.TinValue!,
                because: "section C — customer TIN MUST appear because customer is B2BRegistered (FR-040)"
            );
        text.Should()
            .Contain(
                fixture.Invoice.GrandTotal.Amount.ToString(
                    "F2",
                    System.Globalization.CultureInfo.InvariantCulture
                ),
                because: "section E — grand total numeric"
            );
        text.Should().Contain("Subtotal", because: "section E — invoice subtotal label");
        text.Should().Contain("VAT total", because: "section E — VAT total label");
        text.Should().Contain("In words", because: "section E — Arabic-words rendering label");
        text.Should().Contain("Posted by", because: "section F — posted-by user identity");
        imageCount
            .Should()
            .BeGreaterThan(
                0,
                because: "section F — Document Verification Seal QR MUST be embedded as an image"
            );
    }

    [Fact]
    public void Customer_Tin_Omitted_On_B2BUnregistered_AndLabelIsTaxInvoice()
    {
        var fixture = NewFixture(CustomerTaxProfileType.B2BUnregistered);
        var pdf = _renderer.Render(fixture.Request);

        var (text, _) = ReadPdf(pdf);

        text.Should().Contain("Tax Invoice");
        text.Should()
            .NotContain(
                "Simplified",
                because: "B2BUnregistered receivers receive a regular Tax Invoice, not a Simplified one"
            );
        text.Should()
            .NotContain(
                "Customer TIN:",
                because: "FR-040 — only B2BRegistered receivers carry a customer TIN line"
            );
    }

    [Fact]
    public void Customer_Tin_Omitted_On_B2CConsumer_AndLabelIsSimplifiedTaxInvoice()
    {
        var fixture = NewFixture(CustomerTaxProfileType.B2CConsumer);
        var pdf = _renderer.Render(fixture.Request);

        var (text, _) = ReadPdf(pdf);

        text.Should()
            .Contain(
                "Simplified Tax Invoice",
                because: "section A — document type label MUST switch to Simplified for B2C receivers"
            );
        text.Should()
            .NotContain(
                "Customer TIN:",
                because: "FR-040 — only B2BRegistered receivers carry a customer TIN line"
            );
    }

    [Fact]
    public void Qr_Seal_Image_Present_On_Every_Invoice()
    {
        foreach (
            var profile in new[]
            {
                CustomerTaxProfileType.B2BRegistered,
                CustomerTaxProfileType.B2BUnregistered,
                CustomerTaxProfileType.B2CConsumer,
            }
        )
        {
            var fixture = NewFixture(profile);
            var pdf = _renderer.Render(fixture.Request);
            var (_, imageCount) = ReadPdf(pdf);
            imageCount
                .Should()
                .BeGreaterThan(0, because: $"section F — QR seal MUST be embedded for {profile}");
        }
    }

    [Fact]
    public void Qr_Seal_Encodes_A_Codec_Verifiable_Payload()
    {
        var fixture = NewFixture(CustomerTaxProfileType.B2BRegistered);

        // Decode the seal that was passed to the renderer and verify it
        // round-trips through the codec — proves the renderer's input
        // is contract-conformant. (The image-extraction-then-decode
        // round-trip from the rendered PDF needs OCR-level QR scanning
        // and is left for the print-fidelity test in T078's spec list.)
        var decoded = DocumentSealCodec.Decode(fixture.Request.SealQrPayload);
        decoded
            .Should()
            .NotBeNull(because: "the seal handed to the renderer MUST be a valid EGT1 seal");
        decoded!.DocumentNumber.Should().Be(fixture.Invoice.DocumentNumber);
    }

    [Fact]
    public void Generated_PDF_Is_Valid_PDF_Bytes()
    {
        var fixture = NewFixture(CustomerTaxProfileType.B2BRegistered);
        var pdf = _renderer.Render(fixture.Request);

        pdf.Should().NotBeNull();
        pdf.Length.Should()
            .BeGreaterThan(1000, because: "a real bilingual invoice PDF is several KB at minimum");

        // PDF magic header.
        pdf.AsSpan(0, 4)
            .ToArray()
            .Should()
            .Equal(
                new byte[] { 0x25, 0x50, 0x44, 0x46 },
                because: "the file MUST start with the PDF magic %PDF"
            );
    }

    [Fact]
    public void Render_Throws_For_Unposted_Draft()
    {
        var fixture = NewFixture(CustomerTaxProfileType.B2BRegistered);
        var draft = SalesInvoice.CreateDraft(
            fixture.Receiver.Id,
            fixture.Receiver.TaxProfile,
            new DateOnly(2026, 5, 7)
        );
        draft.AddLine(Guid.NewGuid(), 1m, MoneyEgp.From(100m), Guid.NewGuid(), 14m);
        var bad = fixture.Request with { Invoice = draft };

        var act = () => _renderer.Render(bad);

        act.Should()
            .Throw<InvalidOperationException>(
                because: "FR-027 / INV-002 — only Posted documents have a stable canonical form to render"
            );
    }

    private static (string Text, int ImageCount) ReadPdf(byte[] pdf)
    {
        using var doc = PdfDocument.Open(pdf);
        var raw = string.Concat(doc.GetPages().Select(p => p.Text));
        var images = doc.GetPages().SelectMany(p => p.GetImages()).Count();
        return (NormalizeLigatures(raw), images);
    }

    /// <summary>
    /// PDF font rendering substitutes common Latin ligatures (fi, fl,
    /// ffi, ffl, ft, st) with single Unicode codepoints in the
    /// FB00–FB06 Alphabetic Presentation Forms block. PdfPig extracts
    /// those codepoints faithfully; for substring matching against
    /// the source strings we normalize them back to their multi-char
    /// equivalents.
    /// </summary>
    private static string NormalizeLigatures(string text) =>
        text.Replace("ﬀ", "ff", StringComparison.Ordinal)
            .Replace("ﬁ", "fi", StringComparison.Ordinal)
            .Replace("ﬂ", "fl", StringComparison.Ordinal)
            .Replace("ﬃ", "ffi", StringComparison.Ordinal)
            .Replace("ﬄ", "ffl", StringComparison.Ordinal)
            .Replace("ﬅ", "st", StringComparison.Ordinal)
            .Replace("ﬆ", "st", StringComparison.Ordinal);

    private sealed record Fixture(
        SalesInvoice Invoice,
        Company Issuer,
        Customer Receiver,
        InvoicePdfRequest Request
    );

    private static Fixture NewFixture(CustomerTaxProfileType profileType)
    {
        var issuer = new Company(
            legalName: new ArabicEnglishText("شركة الاختبار", "Test Company SAE"),
            taxRegistrationNumber: EgyptianTin.Parse("123456789"),
            commercialRegistrationNumber: "CR-001234",
            address: PostalAddress.Create(
                display: new ArabicEnglishText("شارع التحرير ١٢", "12 Tahrir Street"),
                governorate: "Cairo",
                regionCity: "Downtown",
                street: "Tahrir",
                buildingNumber: "12",
                postalCode: "11511"
            ),
            taxpayerActivityCode: "0001"
        );

        var vat = new VatCategory(
            code: "Standard",
            name: new ArabicEnglishText("قياسي", "Standard"),
            ratePercent: 14m,
            effectiveFromDate: new DateOnly(2026, 1, 1),
            effectiveToDate: null,
            recoverableInputVat: true
        );

        var item = new Item(
            code: "ITEM-001",
            name: new ArabicEnglishText("ساعة استشارة", "Consulting Hour"),
            defaultVatCategoryId: vat.Id
        );

        var customerAddress = PostalAddress.Create(
            display: new ArabicEnglishText("شارع النيل ٤٥", "45 Nile Street"),
            governorate: "Giza",
            regionCity: "Dokki",
            street: "Nile",
            buildingNumber: "45"
        );

        var taxProfile = profileType switch
        {
            CustomerTaxProfileType.B2BRegistered => CustomerTaxProfile.B2BRegistered(
                EgyptianTin.Parse("987654321"),
                false,
                vat.Id
            ),
            CustomerTaxProfileType.B2BUnregistered => CustomerTaxProfile.B2BUnregistered(
                false,
                vat.Id
            ),
            CustomerTaxProfileType.B2CConsumer => CustomerTaxProfile.B2CConsumer(false, vat.Id),
            _ => throw new ArgumentOutOfRangeException(nameof(profileType)),
        };
        var receiver = new Customer(
            code: "CUST-001",
            name: new ArabicEnglishText("عميل تجريبي", "Test Customer LLC"),
            address: customerAddress,
            taxProfile: taxProfile,
            phone: "+20 10 1234 5678"
        );

        var draft = SalesInvoice.CreateDraft(
            receiver.Id,
            receiver.TaxProfile,
            new DateOnly(2026, 5, 7)
        );
        draft.AddLine(
            item.Id,
            quantity: 1m,
            unitPrice: MoneyEgp.From(1_000m),
            vatCategoryId: vat.Id,
            vatRatePercent: vat.RatePercent
        );
        draft.MarkPosted(
            documentNumber: "INV-2026-000123",
            postedByUserId: Guid.NewGuid(),
            postedAtUtc: new DateTime(2026, 5, 7, 11, 0, 0, DateTimeKind.Utc),
            postingMode: DocumentPostingMode.UnapprovedDirect,
            approvalEnabled: false
        );

        var sealPayload = DocumentSealCodec.Encode(
            new DocumentSealPayload(
                DocumentType: SealedDocumentType.SalesInvoice,
                DocumentNumber: draft.DocumentNumber!,
                DocumentId: draft.Id,
                GrandTotalPiastres: (long)(draft.GrandTotal.Amount * 100m),
                AuditEntryHash: new byte[32],
                AuditEntryIndex: 1L,
                VerifyUrl: "/verify",
                IssuerTin: issuer.TaxRegistrationNumber
            )
        );

        var items = new Dictionary<Guid, ItemRenderInfo> { [item.Id] = new(item.Code, item.Name) };
        var vats = new Dictionary<Guid, VatCategoryRenderInfo>
        {
            [vat.Id] = new(vat.Code, vat.Name, vat.RatePercent),
        };
        var request = new InvoicePdfRequest(
            Invoice: draft,
            Issuer: issuer,
            Receiver: receiver,
            Items: items,
            VatCategories: vats,
            PostedByUserDisplayName: "Test Operator",
            SealQrPayload: sealPayload
        );

        return new Fixture(draft, issuer, receiver, request);
    }
}
