using System.Globalization;
using EgyptTax.Application.Audit;
using EgyptTax.Application.FixedAssets;
using EgyptTax.Domain.Accounting;
using EgyptTax.Domain.Audit;
using EgyptTax.Domain.Documents;
using EgyptTax.Infrastructure.Persistence;
using EgyptTax.SharedKernel;
using EgyptTax.SharedKernel.Time;
using Microsoft.EntityFrameworkCore;

namespace EgyptTax.Infrastructure.BackgroundJobs;

/// <summary>
/// T185 / FR-017 / US6 — monthly depreciation runner. For each
/// InService FixedAsset, looks up the depreciation amount for the
/// requested period via <see cref="DepreciationEngine"/> and emits
/// a balanced 2-line auto-generated JournalVoucher:
///
///   DR  5100 DepreciationExpense   (period amount)
///   CR  1290 AccumulatedDepreciation (period amount)
///
/// Idempotent at the (asset, period) grain — a re-run of the same
/// period is a no-op (skips assets that already have a JV with
/// SourceDocumentId = asset.Id AND Date = period). Without this an
/// inadvertent double-tick would double-depreciate every asset.
///
/// Drift control: per FR-014 spec, depreciation is NOT entered as
/// an Expense aggregate row — only the GL effect lands. The
/// purchase + expense registers therefore exclude depreciation;
/// the journal-listing register (T233) shows it. The trial balance
/// reads from journal entries directly so depreciation flows
/// through unchanged.
/// </summary>
public sealed class MonthlyDepreciationJob
{
    /// <summary>System actor id for auto-generated bookkeeping —
    /// fixed UUID so the audit trail can filter "system actions"
    /// distinctly from operator actions.</summary>
    public static readonly Guid SystemActorId = new("00000000-0000-0000-0000-000000000001");

    private readonly AppDbContext _db;
    private readonly IClock _clock;
    private readonly IAuditLogStore _auditLog;

    public MonthlyDepreciationJob(
        AppDbContext db, IClock clock, IAuditLogStore auditLog)
    {
        _db = db;
        _clock = clock;
        _auditLog = auditLog;
    }

    public async Task<MonthlyDepreciationJobResult> RunForPeriodAsync(
        DateOnly periodFirstDay, CancellationToken cancellationToken = default)
    {
        // Normalise to first-of-month — defensive against callers
        // that pass an arbitrary day in the period.
        var period = new DateOnly(periodFirstDay.Year, periodFirstDay.Month, 1);
        var nowUtc = _clock.UtcNow;

        var assets = await _db.Set<FixedAsset>().AsNoTracking()
            .Where(a => a.Status == FixedAssetStatus.InService)
            .ToListAsync(cancellationToken);

        // Pre-load all auto-depreciation vouchers already posted for
        // this period across the asset set so the per-asset
        // idempotency check is O(1) rather than a per-iteration query.
        var assetIds = assets.Select(a => a.Id).ToArray();
        var alreadyPosted = (await _db.Set<JournalVoucher>().AsNoTracking()
            .Where(v => v.IsAutoGenerated
                && v.Date == period
                && v.SourceDocumentId != null
                && assetIds.Contains(v.SourceDocumentId!.Value))
            .Select(v => v.SourceDocumentId!.Value)
            .ToListAsync(cancellationToken)).ToHashSet();

        var emitted = 0;
        var skipped = 0;

        foreach (var asset in assets)
        {
            if (alreadyPosted.Contains(asset.Id))
            {
                skipped++;
                continue;
            }

            // Pull the single line for this period (or none if the
            // asset hasn't reached the period yet / has run out of
            // useful life).
            var lines = DepreciationEngine.ComputeMonthlySchedule(
                asset, fromMonth: period, throughMonth: period);
            if (lines.Count == 0 || lines[0].Amount.Amount <= 0m)
            {
                continue;
            }
            var line = lines[0];

            var voucher = JournalVoucher.CreateAutoDepreciation(
                periodDate: period,
                narration: new ArabicEnglishText(
                    $"إهلاك شهري — {asset.Code}",
                    $"Monthly depreciation — {asset.Code}"),
                systemUserId: SystemActorId,
                createdAtUtc: nowUtc,
                fixedAssetId: asset.Id,
                lines: new[]
                {
                    (ChartOfAccountCodes.DepreciationExpense, line.Amount, MoneyEgp.Zero,
                        $"Depreciation expense — {asset.Code}"),
                    (ChartOfAccountCodes.AccumulatedDepreciation, MoneyEgp.Zero, line.Amount,
                        $"Accumulated depreciation — {asset.Code}"),
                });

            _db.Add(voucher);
            emitted++;
        }

        if (emitted > 0)
        {
            await _db.SaveChangesAsync(cancellationToken);

            await _auditLog.AppendAsync(new AuditLogPayload(
                Kind: "fixed_asset.monthly_depreciation_run",
                ActorUserId: SystemActorId,
                ActorFirmName: null, CompanyId: Guid.Empty,
                PayloadJson: $$"""{"period":"{{period:yyyy-MM-dd}}","emitted":{{emitted}},"skipped_already_posted":{{skipped}},"total_in_service":{{assets.Count}},"run_at_utc":"{{nowUtc.ToString("o", CultureInfo.InvariantCulture)}}"}"""),
                cancellationToken);
        }

        return new MonthlyDepreciationJobResult(
            Period: period,
            EmittedVoucherCount: emitted,
            SkippedAlreadyPostedCount: skipped,
            InServiceAssetCount: assets.Count);
    }
}

/// <summary>Outcome of one <see cref="MonthlyDepreciationJob.RunForPeriodAsync"/>
/// tick. Surfaced so integration tests + future ops dashboards can
/// see what the job did.</summary>
public sealed record MonthlyDepreciationJobResult(
    DateOnly Period,
    int EmittedVoucherCount,
    int SkippedAlreadyPostedCount,
    int InServiceAssetCount);
