namespace EgyptTax.Application.Compliance.CertificateMonitor;

/// <summary>
/// A signing certificate found in the Windows certificate store
/// (LocalMachine\My). The Penalty Shield narrative depends on the ETA
/// signing cert being valid; an expired cert means every submission
/// fails 401, which is one of the most common Egyptian-accountant
/// "Saturday morning" disasters.
/// </summary>
public sealed record CertificateInfo(
    string Thumbprint,
    string Subject,
    string Issuer,
    DateTime NotBeforeUtc,
    DateTime NotAfterUtc,
    string FriendlyName,
    bool HasPrivateKey,
    CertificateRole Role,
    int DaysUntilExpiry,
    CertificateUrgency Urgency)
{
    public bool IsExpired => DaysUntilExpiry < 0;
    public bool IsExpiringSoon => DaysUntilExpiry >= 0 && DaysUntilExpiry <= 30;
}

/// <summary>What the cert is used for, derived from subject/friendly name.</summary>
public enum CertificateRole
{
    /// <summary>HTTPS cert generated by setup-https.ps1 for Kestrel binding.</summary>
    DaftarXHttps,
    /// <summary>ETA eSeal / signing cert (production e-invoice signing).</summary>
    EtaSigning,
    /// <summary>Other cert in the store, surfaced for completeness.</summary>
    Other,
}

/// <summary>
/// Urgency tone driven by NotAfterUtc - now. The thresholds match the
/// Penalty Shield alert cadence (T-30 / T-14 / T-7 / T-1).
/// </summary>
public enum CertificateUrgency
{
    /// <summary>More than 30 days remaining. All clear.</summary>
    Healthy = 0,
    /// <summary>14-30 days remaining. Plan renewal.</summary>
    PlanRenewal = 1,
    /// <summary>7-14 days remaining. Renew this week.</summary>
    RenewSoon = 2,
    /// <summary>1-7 days remaining. Renew TODAY.</summary>
    Critical = 3,
    /// <summary>Already expired. Submissions will 401.</summary>
    Expired = 4,
}

public interface ICertificateMonitorQuery
{
    /// <summary>
    /// Lists certs in LocalMachine\My that are relevant to DaftarX
    /// (HTTPS + ETA signing). Returns sorted: expired first, then by
    /// nearest expiry.
    /// </summary>
    IReadOnlyList<CertificateInfo> List(DateTime nowUtc);
}
