// <auto-generated />
using System;
using System.Collections.Generic;
using EgyptTax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptTax.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507105423_NumberingCore")]
    partial class NumberingCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptTax.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<string>("ActorFirmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("actor_firm_name");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("PrevHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("prev_hash");

                    b.Property<byte[]>("ThisHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("this_hash");

                    b.Property<DateTime>("TsUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ts_utc");

                    b.HasKey("Index");

                    b.HasIndex("TsUtc")
                        .HasDatabaseName("ix_audit_log_ts_utc");

                    b.HasIndex("CompanyId", "TsUtc")
                        .HasDatabaseName("ix_audit_log_company_ts");

                    b.ToTable("audit_log", "audit");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "EgyptTax.Domain.Identity.Permission.Description#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("description_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("description_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_code");

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<bool>("RequiresMfa")
                        .HasColumnType("bit")
                        .HasColumnName("requires_mfa");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EgyptTax.Domain.Identity.Role.Name#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_code");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_login_at_utc");

                    b.Property<bool>("LastLoginSucceeded")
                        .HasColumnType("bit")
                        .HasColumnName("last_login_succeeded");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("lockout_until_utc");

                    b.Property<DateTime?>("MfaEnrolledAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("mfa_enrolled_at_utc");

                    b.Property<byte[]>("MfaSecretEncrypted")
                        .HasColumnType("varbinary(512)")
                        .HasColumnName("mfa_secret_encrypted");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PasswordMustChange")
                        .HasColumnType("bit")
                        .HasColumnName("password_must_change");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("DisplayName", "EgyptTax.Domain.Identity.User.DisplayName#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("display_name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("display_name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Numbering.DocumentNumberAllocator", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("series_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_year");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int")
                        .HasColumnName("next_number");

                    b.HasKey("SeriesId", "FiscalYear");

                    b.ToTable("document_number_allocator", "numbering");
                });

            modelBuilder.Entity("EgyptTax.Domain.Numbering.DocumentSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("document_type");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EgyptTax.Domain.Numbering.DocumentSeries.Name#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_document_series_code");

                    b.HasIndex("DocumentType")
                        .IsUnique()
                        .HasDatabaseName("ux_document_series_doc_type");

                    b.ToTable("document_series", "numbering");
                });

            modelBuilder.Entity("EgyptTax.Domain.Workflow.DocumentTypeApprovalSetting", b =>
                {
                    b.Property<string>("DocumentType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("document_type");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("bit")
                        .HasColumnName("approval_required");

                    b.HasKey("DocumentType");

                    b.ToTable("document_type_approval_settings", "workflow");

                    b.HasData(
                        new
                        {
                            DocumentType = "SalesInvoice",
                            ApprovalRequired = false
                        },
                        new
                        {
                            DocumentType = "CreditNote",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "PurchaseInvoice",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "Expense",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "JournalVoucher",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "SupplierPaymentVoucher",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "CustomerReceiptVoucher",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "FixedAsset",
                            ApprovalRequired = true
                        });
                });

            modelBuilder.Entity("EgyptTax.Infrastructure.Audit.AuditCheckpointRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<byte[]>("LastHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("last_hash");

                    b.Property<long>("LastIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("last_index");

                    b.Property<DateTime>("TsUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ts_utc");

                    b.HasKey("Id");

                    b.ToTable("checkpoint", "audit_meta", t =>
                        {
                            t.HasCheckConstraint("ck_audit_checkpoint_single_row", "[id] = 1");
                        });
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Numbering.DocumentNumberAllocator", b =>
                {
                    b.HasOne("EgyptTax.Domain.Numbering.DocumentSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("EgyptTax.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptTax.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("EgyptTax.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptTax.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
