// <auto-generated />
using System;
using System.Collections.Generic;
using EgyptTax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptTax.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507171432_CreditNoteApprovalDefault")]
    partial class CreditNoteApprovalDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptTax.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<string>("ActorFirmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("actor_firm_name");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("PrevHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("prev_hash");

                    b.Property<byte[]>("ThisHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("this_hash");

                    b.Property<DateTime>("TsUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ts_utc");

                    b.HasKey("Index");

                    b.HasIndex("TsUtc")
                        .HasDatabaseName("ix_audit_log_ts_utc");

                    b.HasIndex("CompanyId", "TsUtc")
                        .HasDatabaseName("ix_audit_log_company_ts");

                    b.ToTable("audit_log", "audit");
                });

            modelBuilder.Entity("EgyptTax.Domain.Eta.EtaSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionUuid")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("submission_uuid");

                    b.Property<DateTime>("SubmissionWindowExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("submission_window_expires_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SalesInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_eta_submissions_sales_invoice_id");

                    b.HasIndex("Status", "SubmissionWindowExpiresAtUtc")
                        .HasDatabaseName("ix_eta_submissions_dashboard");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "SubmissionWindowExpiresAtUtc"), new[] { "SalesInvoiceId", "AttemptCount", "ErrorCode" });

                    b.ToTable("eta_submissions", "eta");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.AdminRecoveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AuditEmittedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("audit_emitted_at_utc");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("machine_name");

                    b.Property<string>("OperatorIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("operator_identity");

                    b.Property<DateTime>("RecoveredAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("recovered_at_utc");

                    b.Property<string>("TargetEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("target_email");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AuditEmittedAtUtc")
                        .HasDatabaseName("ix_admin_recovery_log_audit_pending")
                        .HasFilter("[audit_emitted_at_utc] IS NULL");

                    b.ToTable("admin_recovery_log", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("IssuedByAdminUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("issued_by_admin_user_id");

                    b.Property<DateTime?>("RedeemedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("redeemed_at_utc");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "EgyptTax.Domain.Identity.Permission.Description#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("description_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("description_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_code");

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<bool>("RequiresMfa")
                        .HasColumnType("bit")
                        .HasColumnName("requires_mfa");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EgyptTax.Domain.Identity.Role.Name#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_code");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbsoluteExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_login_at_utc");

                    b.Property<bool>("LastLoginSucceeded")
                        .HasColumnType("bit")
                        .HasColumnName("last_login_succeeded");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("lockout_until_utc");

                    b.Property<DateTime?>("MfaEnrolledAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("mfa_enrolled_at_utc");

                    b.Property<byte[]>("MfaSecretEncrypted")
                        .HasColumnType("varbinary(512)")
                        .HasColumnName("mfa_secret_encrypted");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PasswordMustChange")
                        .HasColumnType("bit")
                        .HasColumnName("password_must_change");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("DisplayName", "EgyptTax.Domain.Identity.User.DisplayName#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("display_name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("display_name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Invoices.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreditNoteOfInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("credit_note_of_invoice_id");

                    b.Property<string>("CreditNoteReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("credit_note_reason");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("document_number");

                    b.Property<decimal>("InvoiceLevelDiscountPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("invoice_level_discount_percent");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("posted_by_user_id");

                    b.Property<string>("PostingMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("posting_mode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("state");

                    b.ComplexProperty<Dictionary<string, object>>("CustomerTaxProfileSnapshot", "EgyptTax.Domain.Invoices.SalesInvoice.CustomerTaxProfileSnapshot#CustomerTaxProfile", b1 =>
                        {
                            b1.Property<Guid?>("DefaultSalesVatCategoryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("customer_tax_profile_snapshot_default_sales_vat_category_id");

                            b1.Property<string>("ProfileType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("customer_tax_profile_snapshot_type");

                            b1.Property<string>("TinValue")
                                .HasMaxLength(9)
                                .IsUnicode(false)
                                .HasColumnType("varchar(9)")
                                .HasColumnName("customer_tax_profile_snapshot_tin");

                            b1.Property<bool>("VatExemption")
                                .HasColumnType("bit")
                                .HasColumnName("customer_tax_profile_snapshot_vat_exemption");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("GrandTotal", "EgyptTax.Domain.Invoices.SalesInvoice.GrandTotal#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("grand_total");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("InvoiceLevelDiscountAmount", "EgyptTax.Domain.Invoices.SalesInvoice.InvoiceLevelDiscountAmount#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("invoice_level_discount_amount");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NetBeforeVat", "EgyptTax.Domain.Invoices.SalesInvoice.NetBeforeVat#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("net_before_vat");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Subtotal", "EgyptTax.Domain.Invoices.SalesInvoice.Subtotal#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("subtotal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("VatTotal", "EgyptTax.Domain.Invoices.SalesInvoice.VatTotal#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("vat_total");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreditNoteOfInvoiceId")
                        .HasDatabaseName("ix_sales_invoices_credit_note_of_invoice_id")
                        .HasFilter("[credit_note_of_invoice_id] IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_invoices_customer_id");

                    b.HasIndex("DocumentNumber")
                        .HasDatabaseName("ix_sales_invoices_document_number");

                    b.ToTable("sales_invoices", "documents");
                });

            modelBuilder.Entity("EgyptTax.Domain.Invoices.SalesInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sales_invoice_id");

                    b.Property<Guid>("VatCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vat_category_id");

                    b.Property<decimal>("VatRatePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.ComplexProperty<Dictionary<string, object>>("LineApportionedDiscount", "EgyptTax.Domain.Invoices.SalesInvoiceLine.LineApportionedDiscount#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("line_apportioned_discount");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LineNetSubtotal", "EgyptTax.Domain.Invoices.SalesInvoiceLine.LineNetSubtotal#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("line_net_subtotal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LineSubtotal", "EgyptTax.Domain.Invoices.SalesInvoiceLine.LineSubtotal#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("line_subtotal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LineTotal", "EgyptTax.Domain.Invoices.SalesInvoiceLine.LineTotal#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("line_total");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LineVat", "EgyptTax.Domain.Invoices.SalesInvoiceLine.LineVat#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,2)")
                                .HasColumnName("line_vat");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitPrice", "EgyptTax.Domain.Invoices.SalesInvoiceLine.UnitPrice#MoneyEgp", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("unit_price");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("sales_invoice_lines", "documents");
                });

            modelBuilder.Entity("EgyptTax.Domain.MasterData.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CommercialRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("commercial_registration_number");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("default_language");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_year_start_month");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("logo_path");

                    b.Property<string>("TaxRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("tax_registration_number");

                    b.Property<string>("TaxpayerActivityCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("taxpayer_activity_code");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "EgyptTax.Domain.MasterData.Company.Address#PostalAddress", b1 =>
                        {
                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .IsUnicode(false)
                                .HasColumnType("varchar(32)")
                                .HasColumnName("address_building_number");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .IsUnicode(false)
                                .HasColumnType("varchar(2)")
                                .HasColumnName("address_country");

                            b1.Property<string>("DisplayArabic")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("address_ar");

                            b1.Property<string>("DisplayEnglish")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("address_en");

                            b1.Property<string>("Governorate")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address_governorate");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("varchar(16)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("RegionCity")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address_region_city");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("address_street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LegalName", "EgyptTax.Domain.MasterData.Company.LegalName#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("legal_name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("legal_name_en");
                        });

                    b.HasKey("Id");

                    b.ToTable("companies", "master");
                });

            modelBuilder.Entity("EgyptTax.Domain.MasterData.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "EgyptTax.Domain.MasterData.Customer.Address#PostalAddress", b1 =>
                        {
                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .IsUnicode(false)
                                .HasColumnType("varchar(32)")
                                .HasColumnName("address_building_number");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .IsUnicode(false)
                                .HasColumnType("varchar(2)")
                                .HasColumnName("address_country");

                            b1.Property<string>("DisplayArabic")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("address_ar");

                            b1.Property<string>("DisplayEnglish")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("address_en");

                            b1.Property<string>("Governorate")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address_governorate");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("varchar(16)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("RegionCity")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address_region_city");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("address_street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EgyptTax.Domain.MasterData.Customer.Name#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name_en");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TaxProfile", "EgyptTax.Domain.MasterData.Customer.TaxProfile#CustomerTaxProfile", b1 =>
                        {
                            b1.Property<Guid?>("DefaultSalesVatCategoryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("tax_profile_default_sales_vat_category_id");

                            b1.Property<string>("ProfileType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("tax_profile_type");

                            b1.Property<string>("TinValue")
                                .HasMaxLength(9)
                                .IsUnicode(false)
                                .HasColumnType("varchar(9)")
                                .HasColumnName("tax_profile_tin");

                            b1.Property<bool>("VatExemption")
                                .HasColumnType("bit")
                                .HasColumnName("tax_profile_vat_exemption");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_code");

                    b.ToTable("customers", "master");
                });

            modelBuilder.Entity("EgyptTax.Domain.MasterData.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<Guid>("DefaultVatCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("default_vat_category_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EgyptTax.Domain.MasterData.Item.Name#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_items_code");

                    b.ToTable("items", "master");
                });

            modelBuilder.Entity("EgyptTax.Domain.MasterData.VatCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_from_date");

                    b.Property<DateOnly?>("EffectiveToDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_to_date");

                    b.Property<decimal>("RatePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("rate_percent");

                    b.Property<bool>("RecoverableInputVat")
                        .HasColumnType("bit")
                        .HasColumnName("recoverable_input_vat");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EgyptTax.Domain.MasterData.VatCategory.Name#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code", "EffectiveFromDate")
                        .IsUnique()
                        .HasDatabaseName("ux_vat_categories_code_effective_from");

                    b.ToTable("vat_categories", "tax");
                });

            modelBuilder.Entity("EgyptTax.Domain.Numbering.DocumentNumberAllocator", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("series_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_year");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int")
                        .HasColumnName("next_number");

                    b.HasKey("SeriesId", "FiscalYear");

                    b.ToTable("document_number_allocator", "numbering");
                });

            modelBuilder.Entity("EgyptTax.Domain.Numbering.DocumentSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("document_type");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "EgyptTax.Domain.Numbering.DocumentSeries.Name#ArabicEnglishText", b1 =>
                        {
                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_document_series_code");

                    b.HasIndex("DocumentType")
                        .IsUnique()
                        .HasDatabaseName("ux_document_series_doc_type");

                    b.ToTable("document_series", "numbering");
                });

            modelBuilder.Entity("EgyptTax.Domain.Workflow.DocumentTypeApprovalSetting", b =>
                {
                    b.Property<string>("DocumentType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("document_type");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("bit")
                        .HasColumnName("approval_required");

                    b.HasKey("DocumentType");

                    b.ToTable("document_type_approval_settings", "workflow");

                    b.HasData(
                        new
                        {
                            DocumentType = "SalesInvoice",
                            ApprovalRequired = false
                        },
                        new
                        {
                            DocumentType = "CreditNote",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "PurchaseInvoice",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "Expense",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "JournalVoucher",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "SupplierPaymentVoucher",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "CustomerReceiptVoucher",
                            ApprovalRequired = true
                        },
                        new
                        {
                            DocumentType = "FixedAsset",
                            ApprovalRequired = true
                        });
                });

            modelBuilder.Entity("EgyptTax.Infrastructure.Audit.AuditCheckpointRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<byte[]>("LastHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("last_hash");

                    b.Property<long>("LastIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("last_index");

                    b.Property<DateTime>("TsUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ts_utc");

                    b.HasKey("Id");

                    b.ToTable("checkpoint", "audit_meta", t =>
                        {
                            t.HasCheckConstraint("ck_audit_checkpoint_single_row", "[id] = 1");
                        });
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("EgyptTax.Domain.Invoices.SalesInvoiceLine", b =>
                {
                    b.HasOne("EgyptTax.Domain.Invoices.SalesInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EgyptTax.Domain.Numbering.DocumentNumberAllocator", b =>
                {
                    b.HasOne("EgyptTax.Domain.Numbering.DocumentSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("EgyptTax.Domain.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptTax.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("EgyptTax.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptTax.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EgyptTax.Domain.Invoices.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
