// <auto-generated />
using System;
using EgyptTax.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptTax.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptTax.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<string>("ActorFirmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("actor_firm_name");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("PrevHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("prev_hash");

                    b.Property<byte[]>("ThisHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("this_hash");

                    b.Property<DateTime>("TsUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ts_utc");

                    b.HasKey("Index");

                    b.HasIndex("TsUtc")
                        .HasDatabaseName("ix_audit_log_ts_utc");

                    b.HasIndex("CompanyId", "TsUtc")
                        .HasDatabaseName("ix_audit_log_company_ts");

                    b.ToTable("audit_log", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
