using EgyptTax.Application.Audit;
using EgyptTax.Domain.Accounting;
using EgyptTax.Domain.Audit;
using EgyptTax.Domain.Documents;
using EgyptTax.Domain.Workflow;
using EgyptTax.Infrastructure.BackgroundJobs;
using EgyptTax.Infrastructure.Persistence;
using EgyptTax.IntegrationTests.Infrastructure;
using EgyptTax.SharedKernel;
using EgyptTax.SharedKernel.Time;
using Microsoft.EntityFrameworkCore;

namespace EgyptTax.IntegrationTests.FixedAssets;

/// <summary>
/// T185 / FR-017 / US6 — RunMonthlyDepreciation Hangfire job.
/// Pins three guarantees:
///   * Every InService asset gets exactly one balanced 2-line
///     auto-generated JournalVoucher per period (DR Depreciation
///     Expense / CR Accumulated Depreciation).
///   * Re-running the same period is a no-op — the (asset, period)
///     idempotency check skips assets that already have a JV.
///   * Draft + Disposed assets are skipped (depreciation runs only
///     for InService).
/// </summary>
[Collection(SqlServerCollection.Name)]
public class MonthlyDepreciationJobTests(SqlServerFixture fixture)
{
    private readonly SqlServerFixture _fixture = fixture;

    [Fact]
    public async Task RunForPeriod_EmitsBalanced2LineVoucher_PerInServiceAsset()
    {
        await using var db = await _fixture.CreateContextAsync();
        var assetA = await SeedInServiceAssetAsync(db, "FA-A", cost: 60_000m,
            inServiceDate: new DateOnly(2026, 1, 1)); // 1000/month
        var assetB = await SeedInServiceAssetAsync(db, "FA-B", cost: 12_000m,
            inServiceDate: new DateOnly(2026, 1, 1)); // 200/month

        var job = new MonthlyDepreciationJob(db,
            new TestClock(new DateTime(2026, 5, 1, 1, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore());

        var result = await job.RunForPeriodAsync(new DateOnly(2026, 5, 1));

        result.EmittedVoucherCount.Should().Be(2);
        result.SkippedAlreadyPostedCount.Should().Be(0);
        result.InServiceAssetCount.Should().Be(2);

        db.ChangeTracker.Clear();
        var vouchers = await db.Set<JournalVoucher>().AsNoTracking()
            .Include(v => v.Lines)
            .Where(v => v.IsAutoGenerated && v.Date == new DateOnly(2026, 5, 1))
            .ToListAsync();

        vouchers.Should().HaveCount(2);

        foreach (var v in vouchers)
        {
            v.IsAutoGenerated.Should().BeTrue();
            v.SourceDocumentType.Should().Be(DocumentType.FixedAsset);
            v.SourceDocumentId.Should().NotBeNull();
            v.Lines.Should().HaveCount(2);

            var debit = v.Lines.Single(l => l.AccountCode == ChartOfAccountCodes.DepreciationExpense);
            var credit = v.Lines.Single(l => l.AccountCode == ChartOfAccountCodes.AccumulatedDepreciation);
            debit.Debit.Amount.Should().Be(credit.Credit.Amount,
                because: "DR Depreciation Expense MUST equal CR Accumulated Depreciation per voucher");
            debit.Credit.Amount.Should().Be(0m);
            credit.Debit.Amount.Should().Be(0m);
        }

        // Per-asset amounts match the engine.
        var voucherA = vouchers.Single(v => v.SourceDocumentId == assetA.Id);
        voucherA.Lines.First(l => l.Debit.Amount > 0m).Debit.Amount.Should().Be(1_000m);
        var voucherB = vouchers.Single(v => v.SourceDocumentId == assetB.Id);
        voucherB.Lines.First(l => l.Debit.Amount > 0m).Debit.Amount.Should().Be(200m);
    }

    [Fact]
    public async Task RerunningSamePeriod_IsIdempotent_AndDoesNotDoubleDepreciate()
    {
        await using var db = await _fixture.CreateContextAsync();
        await SeedInServiceAssetAsync(db, "FA-IDEMPOTENT", cost: 60_000m,
            inServiceDate: new DateOnly(2026, 1, 1));

        var job = new MonthlyDepreciationJob(db,
            new TestClock(new DateTime(2026, 5, 1, 1, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore());

        var first = await job.RunForPeriodAsync(new DateOnly(2026, 5, 1));
        first.EmittedVoucherCount.Should().Be(1);

        // Second tick MUST be a no-op — without the (asset, period)
        // idempotency check an inadvertent double-tick would
        // double-depreciate every asset.
        var second = await job.RunForPeriodAsync(new DateOnly(2026, 5, 1));
        second.EmittedVoucherCount.Should().Be(0);
        second.SkippedAlreadyPostedCount.Should().Be(1,
            because: "the asset already has a JV for this period; re-run MUST skip it");

        var totalVouchers = await db.Set<JournalVoucher>().AsNoTracking()
            .CountAsync(v => v.IsAutoGenerated && v.Date == new DateOnly(2026, 5, 1));
        totalVouchers.Should().Be(1,
            because: "exactly one JV per asset per period regardless of how many times the job ticks");
    }

    [Fact]
    public async Task DraftAndDisposedAssets_AreSkipped()
    {
        await using var db = await _fixture.CreateContextAsync();
        // Draft asset — no PutInService called.
        var draft = FixedAsset.CreateDraft(
            code: "FA-DRAFT", description: new ArabicEnglishText("مسودة", "Draft"),
            assetCategory: "Equipment", cost: MoneyEgp.From(60_000m),
            inServiceDate: new DateOnly(2026, 1, 1), usefulLifeMonths: 60,
            depreciationMethod: DepreciationMethod.StraightLine,
            salvageValue: MoneyEgp.Zero, convention: DepreciationConvention.FullMonth);
        db.Add(draft);

        // Disposed asset — InService then disposed before the period.
        var disposed = FixedAsset.CreateDraft(
            code: "FA-DISPOSED", description: new ArabicEnglishText("متصرف", "Disposed"),
            assetCategory: "Equipment", cost: MoneyEgp.From(60_000m),
            inServiceDate: new DateOnly(2026, 1, 1), usefulLifeMonths: 60,
            depreciationMethod: DepreciationMethod.StraightLine,
            salvageValue: MoneyEgp.Zero, convention: DepreciationConvention.FullMonth);
        disposed.PutInService();
        disposed.Dispose(new DateOnly(2026, 4, 30));
        db.Add(disposed);

        await db.SaveChangesAsync();

        var job = new MonthlyDepreciationJob(db,
            new TestClock(new DateTime(2026, 5, 1, 1, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore());

        var result = await job.RunForPeriodAsync(new DateOnly(2026, 5, 1));

        result.EmittedVoucherCount.Should().Be(0,
            because: "Draft + Disposed assets are skipped — depreciation runs ONLY for InService");
        result.InServiceAssetCount.Should().Be(0,
            because: "neither Draft nor Disposed counts as InService");
    }

    [Fact]
    public async Task AssetsBeforeInService_OrPastUsefulLife_AreSkippedQuietly()
    {
        await using var db = await _fixture.CreateContextAsync();
        // In-service in June 2026 — May 2026 run should produce no
        // line for it (period precedes in-service date).
        await SeedInServiceAssetAsync(db, "FA-FUTURE", cost: 60_000m,
            inServiceDate: new DateOnly(2026, 6, 15));

        var job = new MonthlyDepreciationJob(db,
            new TestClock(new DateTime(2026, 5, 1, 1, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore());

        var result = await job.RunForPeriodAsync(new DateOnly(2026, 5, 1));

        result.EmittedVoucherCount.Should().Be(0,
            because: "asset's in-service date is in June; the May run produces no line for it");
        result.InServiceAssetCount.Should().Be(1,
            because: "the asset IS InService — the engine just returns no period line");
    }

    private static async Task<FixedAsset> SeedInServiceAssetAsync(
        AppDbContext db, string code, decimal cost, DateOnly inServiceDate)
    {
        var asset = FixedAsset.CreateDraft(
            code: code,
            description: new ArabicEnglishText("معدات", $"Asset {code}"),
            assetCategory: "Equipment",
            cost: MoneyEgp.From(cost),
            inServiceDate: inServiceDate,
            usefulLifeMonths: 60,
            depreciationMethod: DepreciationMethod.StraightLine,
            salvageValue: MoneyEgp.Zero,
            convention: DepreciationConvention.FullMonth);
        asset.PutInService();
        db.Add(asset);
        await db.SaveChangesAsync();
        return asset;
    }

    private sealed class TestClock(DateTime utcNow) : IClock
    {
        public DateTime UtcNow { get; } = utcNow;
    }

    private sealed class CaptureAuditLogStore : IAuditLogStore
    {
        public List<AuditLogPayload> Captured { get; } = [];
        public Task<AuditLogEntry> AppendAsync(AuditLogPayload payload, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(payload);
            Captured.Add(payload);
            return Task.FromResult(new AuditLogEntry(
                index: Captured.Count, tsUtc: DateTime.UtcNow,
                actorUserId: payload.ActorUserId, actorFirmName: payload.ActorFirmName,
                companyId: payload.CompanyId, kind: payload.Kind, payloadJson: payload.PayloadJson,
                prevHash: new byte[32], thisHash: new byte[32]));
        }
    }
}
