// <auto-generated />
using System;
using EgyptTax.Portal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptTax.Portal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260518013851_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EgyptTax.Portal.Infrastructure.Identity.PortalRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_portal_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("portal_roles", (string)null);
                });

            modelBuilder.Entity("EgyptTax.Portal.Infrastructure.Identity.PortalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("LocalePreference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("locale_preference");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime?>("SoftDeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("soft_deleted_at_utc");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_team_members");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("EgyptTax.Portal.Infrastructure.Persistence.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActorDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_display_name_snapshot");

                    b.Property<Guid?>("ActorTeamMemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_team_member_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organisation_id");

                    b.Property<string>("OriginatingIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("originating_ip");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_kind");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("verb");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("Verb");

                    b.HasIndex("OrganisationId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_audit_log_entries_org_occurred_desc");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("EgyptTax.Portal.Infrastructure.Persistence.Entities.CustomerOrganisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BillingAddressJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("billing_address_json");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("billing_email");

                    b.Property<string>("BillingPhone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("billing_phone");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LegalNameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("legal_name_ar");

                    b.Property<string>("LegalNameEn")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("legal_name_en");

                    b.Property<bool>("RequiresMfaForOwners")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_mfa_for_owners");

                    b.Property<DateTime?>("SoftDeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("soft_deleted_at_utc");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_registration_number");

                    b.HasKey("Id")
                        .HasName("pk_customer_organisations");

                    b.HasIndex("BillingEmail");

                    b.HasIndex("SoftDeletedAtUtc")
                        .HasFilter("[soft_deleted_at_utc] IS NOT NULL");

                    b.ToTable("customer_organisations", (string)null);
                });

            modelBuilder.Entity("EgyptTax.Portal.Infrastructure.Persistence.Entities.OrganisationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at_utc");

                    b.Property<DateTime>("InvitedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("invited_at_utc");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("organisation_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<int>("SecurityStampVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("security_stamp_version");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("team_member_id");

                    b.HasKey("Id")
                        .HasName("pk_organisation_memberships");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("OrganisationId", "TeamMemberId")
                        .IsUnique()
                        .HasDatabaseName("UX_organisation_memberships_active_org_member")
                        .HasFilter("[revoked_at_utc] IS NULL");

                    b.ToTable("organisation_memberships", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_portal_role_claims");

                    b.HasIndex("RoleId");

                    b.ToTable("portal_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_team_member_claims");

                    b.HasIndex("UserId");

                    b.ToTable("team_member_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_team_member_logins");

                    b.HasIndex("UserId");

                    b.ToTable("team_member_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_team_member_roles");

                    b.HasIndex("RoleId");

                    b.ToTable("team_member_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_team_member_tokens");

                    b.ToTable("team_member_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("EgyptTax.Portal.Infrastructure.Identity.PortalRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portal_role_claims_portal_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EgyptTax.Portal.Infrastructure.Identity.PortalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_claims_team_members_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EgyptTax.Portal.Infrastructure.Identity.PortalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_logins_team_members_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("EgyptTax.Portal.Infrastructure.Identity.PortalRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_roles_portal_roles_role_id");

                    b.HasOne("EgyptTax.Portal.Infrastructure.Identity.PortalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_roles_team_members_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EgyptTax.Portal.Infrastructure.Identity.PortalUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_tokens_team_members_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
