using EgyptTax.Domain.Documents;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EgyptTax.Infrastructure.Persistence;

internal sealed class JournalVoucherConfiguration : IEntityTypeConfiguration<JournalVoucher>
{
    public void Configure(EntityTypeBuilder<JournalVoucher> b)
    {
        b.ToTable("journal_vouchers", schema: "accounting");
        b.HasKey(v => v.Id);
        b.Property(v => v.Id).HasColumnName("id").ValueGeneratedNever();

        b.Property(v => v.Date).HasColumnName("date").HasColumnType("date").IsRequired();
        b.Property(v => v.SourceDocumentType)
            .HasColumnName("source_document_type")
            .HasConversion<string>().HasMaxLength(32);
        b.Property(v => v.SourceDocumentId).HasColumnName("source_document_id");
        b.Property(v => v.IsAutoGenerated).HasColumnName("is_auto_generated").IsRequired();
        b.Property(v => v.ReversesJournalVoucherId).HasColumnName("reverses_journal_voucher_id");
        b.Property(v => v.CreatedByUserId).HasColumnName("created_by_user_id").IsRequired();
        b.Property(v => v.CreatedAtUtc).HasColumnName("created_at_utc").HasColumnType("datetime2(3)").IsRequired();

        b.ComplexProperty(v => v.Narration, n =>
        {
            n.Property(x => x.Arabic).HasColumnName("narration_ar").HasMaxLength(500).IsRequired();
            n.Property(x => x.English).HasColumnName("narration_en").HasMaxLength(500).IsRequired();
        });

        b.HasMany(v => v.Lines)
            .WithOne()
            .HasForeignKey(l => l.JournalVoucherId)
            .OnDelete(DeleteBehavior.Cascade);

        b.Metadata.FindNavigation(nameof(JournalVoucher.Lines))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);

        b.HasIndex(v => v.Date).HasDatabaseName("ix_journal_vouchers_date");
        b.HasIndex(v => v.ReversesJournalVoucherId)
            .HasDatabaseName("ix_journal_vouchers_reverses_journal_voucher_id")
            .HasFilter("[reverses_journal_voucher_id] IS NOT NULL");
        b.HasIndex(v => v.SourceDocumentId)
            .HasDatabaseName("ix_journal_vouchers_source_document_id")
            .HasFilter("[source_document_id] IS NOT NULL");
    }
}
