using EgyptTax.Application.Identity;
using EgyptTax.Domain.Identity;
using EgyptTax.Infrastructure.Persistence;
using EgyptTax.SharedKernel;
using Microsoft.EntityFrameworkCore;

namespace EgyptTax.Infrastructure.Settings;

/// <summary>
/// Gux.13 Tab 6 — user-management commands. Adds/disables/resets/
/// deletes users with role assignment. Edition-gating happens
/// upstream in the UI (EditionGate.Require(Feature.MultiUser));
/// this handler handles the data layer once allowed.
///
/// Password rules: temp passwords are operator-supplied (or
/// auto-generated by GenerateTempPassword), hashed with Argon2id,
/// and the user is created with PasswordMustChange = true so the
/// first login forces them through /password/change.
/// </summary>
public sealed class UserManagementHandler
{
    private readonly AppDbContext _db;
    private readonly IPasswordHasher _hasher;

    public UserManagementHandler(AppDbContext db, IPasswordHasher hasher)
    {
        _db = db;
        _hasher = hasher;
    }

    public async Task<List<UserSummary>> ListAsync(CancellationToken ct = default)
    {
        return await _db.Set<User>().AsNoTracking()
            .Include(u => u.Roles)
            .OrderBy(u => u.Email)
            .Select(u => new UserSummary(
                u.Id,
                u.Email,
                u.DisplayName.Arabic,
                u.DisplayName.English,
                u.Roles.Select(r => r.Code).ToList(),
                u.Status,
                u.LastLoginAtUtc,
                u.CommissionRatePercent))
            .ToListAsync(ct);
    }

    public async Task SetCommissionRateAsync(Guid userId, decimal? ratePercent, CancellationToken ct = default)
    {
        var user = await _db.Set<User>().FirstOrDefaultAsync(u => u.Id == userId, ct)
            ?? throw new InvalidOperationException($"User {userId} not found.");
        user.SetCommissionRate(ratePercent);
        await _db.SaveChangesAsync(ct);
    }

    public async Task<List<RoleSummary>> ListRolesAsync(CancellationToken ct = default)
    {
        return await _db.Set<Role>().AsNoTracking()
            .OrderBy(r => r.Code)
            .Select(r => new RoleSummary(r.Id, r.Code, r.Name.Arabic, r.Name.English))
            .ToListAsync(ct);
    }

    public async Task<UserSummary> AddAsync(AddUserCommand command, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(command);
        ArgumentException.ThrowIfNullOrWhiteSpace(command.Email);
        ArgumentException.ThrowIfNullOrWhiteSpace(command.TempPassword);
        ArgumentException.ThrowIfNullOrWhiteSpace(command.RoleCode);

#pragma warning disable CA1308 // Email canonical form is lowercase per RFC 5321; matches User entity behavior.
        var canonicalEmail = command.Email.Trim().ToLowerInvariant();
#pragma warning restore CA1308
        if (await _db.Set<User>().AnyAsync(u => u.Email == canonicalEmail, ct))
        {
            throw new InvalidOperationException(
                $"A user with email '{canonicalEmail}' already exists.");
        }

        var role = await _db.Set<Role>().FirstOrDefaultAsync(r => r.Code == command.RoleCode, ct)
            ?? throw new InvalidOperationException($"Role '{command.RoleCode}' not found.");

        var hashed = _hasher.Hash(command.TempPassword);
        var user = new User(
            email: canonicalEmail,
            displayName: new ArabicEnglishText(
                command.DisplayNameAr ?? canonicalEmail,
                command.DisplayNameEn ?? canonicalEmail),
            passwordHash: hashed,
            preferredLanguage: command.PreferredLanguage,
            passwordMustChange: true);
        user.Roles.Add(role);

        _db.Add(user);
        await _db.SaveChangesAsync(ct);

        return new UserSummary(
            user.Id, user.Email, user.DisplayName.Arabic, user.DisplayName.English,
            new List<string> { role.Code }, user.Status, null, user.CommissionRatePercent);
    }

    public async Task DisableAsync(Guid userId, CancellationToken ct = default)
    {
        var user = await _db.Set<User>().FirstOrDefaultAsync(u => u.Id == userId, ct)
            ?? throw new InvalidOperationException($"User {userId} not found.");
        user.Disable();
        await _db.SaveChangesAsync(ct);
    }

    public async Task ReactivateAsync(Guid userId, CancellationToken ct = default)
    {
        var user = await _db.Set<User>().FirstOrDefaultAsync(u => u.Id == userId, ct)
            ?? throw new InvalidOperationException($"User {userId} not found.");
        user.Reactivate();
        await _db.SaveChangesAsync(ct);
    }

    public async Task<string> ResetPasswordAsync(Guid userId, string newTempPassword, CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(newTempPassword);
        var user = await _db.Set<User>().FirstOrDefaultAsync(u => u.Id == userId, ct)
            ?? throw new InvalidOperationException($"User {userId} not found.");
        var hashed = _hasher.Hash(newTempPassword);
        user.SetPassword(hashed, mustChange: true);
        await _db.SaveChangesAsync(ct);
        return newTempPassword;
    }

    public async Task DeleteAsync(Guid userId, CancellationToken ct = default)
    {
        var user = await _db.Set<User>().FirstOrDefaultAsync(u => u.Id == userId, ct)
            ?? throw new InvalidOperationException($"User {userId} not found.");
        _db.Remove(user);
        await _db.SaveChangesAsync(ct);
    }

    /// <summary>Generate a 12-char temp password the operator can
    /// hand to the new user — typically over WhatsApp or by phone,
    /// so the alphabet excludes glyphs that get garbled when
    /// dictated: 0, O, o, 1, I, i, L, l. Same philosophy as
    /// ReferralCode but with mixed case + digits + symbols so the
    /// result passes typical complexity policies.
    /// </summary>
    public static string GenerateTempPassword()
    {
        // Excluded: 0 O o, 1 I i, L l. Rest is mixed case + digits + punctuation.
        const string alphabet = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#$";
        var bytes = new byte[12];
        System.Security.Cryptography.RandomNumberGenerator.Fill(bytes);
        var chars = new char[12];
        for (var i = 0; i < 12; i++)
        {
            chars[i] = alphabet[bytes[i] % alphabet.Length];
        }
        return new string(chars);
    }
}

public sealed record UserSummary(
    Guid Id,
    string Email,
    string DisplayNameAr,
    string DisplayNameEn,
    IReadOnlyList<string> RoleCodes,
    UserStatus Status,
    DateTime? LastLoginAtUtc,
    decimal? CommissionRatePercent);

public sealed record RoleSummary(
    Guid Id,
    string Code,
    string NameAr,
    string NameEn);

public sealed record AddUserCommand(
    string Email,
    string? DisplayNameAr,
    string? DisplayNameEn,
    string TempPassword,
    string RoleCode,
    Language PreferredLanguage = Language.Ar);
