<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EgyptTax.Infrastructure</RootNamespace>
    <AssemblyName>EgyptTax.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EgyptTax.Application\EgyptTax.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Dapper" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="Otp.NET" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="System.Formats.Cbor" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="Polly" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
  </ItemGroup>

</Project>
