using EgyptTax.Application.Audit;
using EgyptTax.Application.Journals;
using EgyptTax.Domain.Audit;
using EgyptTax.Domain.Documents;
using EgyptTax.Domain.Identity;
using EgyptTax.Infrastructure.Journals;
using EgyptTax.Infrastructure.Persistence;
using EgyptTax.IntegrationTests.Infrastructure;
using EgyptTax.SharedKernel;
using EgyptTax.SharedKernel.Time;
using Microsoft.EntityFrameworkCore;

namespace EgyptTax.IntegrationTests.Journals;

/// <summary>
/// T167 / FR-030 — a manual adjusting journal voucher with
/// unbalanced lines (SUM(debit) ≠ SUM(credit)) MUST be refused
/// before it ever lands in the database. The check happens inside
/// <see cref="JournalVoucher.CreateManual"/> so an unbalanced
/// caller cannot construct a JournalVoucher instance — the
/// EF Save downstream is unreachable on that path.
///
/// Also asserts that a properly-balanced manual voucher persists
/// cleanly + emits the FR-028 audit event, so we know the failure
/// case isn't a side-effect of the handler refusing every voucher.
/// </summary>
[Collection(SqlServerCollection.Name)]
public class ManualJournalBalanceGuardTests(SqlServerFixture fixture)
{
    private readonly SqlServerFixture _fixture = fixture;

    [Fact]
    public async Task UnbalancedManualJournal_IsRefused_BeforeDbSave()
    {
        await using var db = await _fixture.CreateContextAsync();
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");
        var handler = BuildHandler(db);

        // 100 in debits vs 50 in credits — clearly unbalanced.
        var command = new CreateManualAdjustingJournalCommand(
            Date: new DateOnly(2026, 5, 8),
            Narration: new ArabicEnglishText("قيد غير متوازن", "Unbalanced test"),
            CreatedByUserId: accountant.Id,
            Lines: new[]
            {
                new ManualJournalLineInput("1200", MoneyEgp.From(100m), MoneyEgp.Zero, "AR debit"),
                new ManualJournalLineInput(
                    "4000",
                    MoneyEgp.Zero,
                    MoneyEgp.From(50m),
                    "Revenue credit (wrong amount)"
                ),
            }
        );

        var act = async () => await handler.HandleAsync(command, CancellationToken.None);

        await act.Should()
            .ThrowAsync<InvalidOperationException>()
            .Where(ex =>
                ex.Message.Contains("unbalanced", StringComparison.OrdinalIgnoreCase)
                || ex.Message.Contains("FR-030", StringComparison.OrdinalIgnoreCase)
            );

        // Critical regression guard: nothing persisted.
        var voucherCount = await db.Set<JournalVoucher>().AsNoTracking().CountAsync();
        voucherCount
            .Should()
            .Be(
                0,
                because: "FR-030 — an unbalanced voucher MUST be refused at the aggregate factory; no JournalVoucher row should exist"
            );
    }

    [Fact]
    public async Task BalancedManualJournal_Succeeds_AndPersistsLines()
    {
        await using var db = await _fixture.CreateContextAsync();
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");
        var handler = BuildHandler(db);

        var command = new CreateManualAdjustingJournalCommand(
            Date: new DateOnly(2026, 5, 8),
            Narration: new ArabicEnglishText("تسوية رواتب", "Payroll accrual adjustment"),
            CreatedByUserId: accountant.Id,
            Lines: new[]
            {
                new ManualJournalLineInput(
                    "5200",
                    MoneyEgp.From(10_000m),
                    MoneyEgp.Zero,
                    "Salary expense"
                ),
                new ManualJournalLineInput(
                    "2200",
                    MoneyEgp.Zero,
                    MoneyEgp.From(10_000m),
                    "Salaries payable"
                ),
            }
        );

        var voucher = await handler.HandleAsync(command, CancellationToken.None);

        voucher.IsAutoGenerated.Should().BeFalse();
        voucher.ReversesJournalVoucherId.Should().BeNull();
        voucher.Lines.Should().HaveCount(2);
        voucher.Lines.Sum(l => l.Debit.Amount).Should().Be(10_000m);
        voucher.Lines.Sum(l => l.Credit.Amount).Should().Be(10_000m);

        // Round-trip the voucher to confirm EF persisted both header
        // + lines correctly.
        db.ChangeTracker.Clear();
        var reloaded = await db.Set<JournalVoucher>()
            .AsNoTracking()
            .Include(v => v.Lines)
            .FirstAsync(v => v.Id == voucher.Id);
        reloaded.Lines.Should().HaveCount(2);
        reloaded.Narration.English.Should().Be("Payroll accrual adjustment");
    }

    [Fact]
    public async Task SingleLineManualJournal_IsRefused_AtAggregateBoundary()
    {
        // The C5 invariant is "≥ 2 lines"; a 1-line voucher can
        // never balance (the one side has no counterpart) and is
        // refused even before the SUM-balance check.
        await using var db = await _fixture.CreateContextAsync();
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");
        var handler = BuildHandler(db);

        var command = new CreateManualAdjustingJournalCommand(
            Date: new DateOnly(2026, 5, 8),
            Narration: new ArabicEnglishText("سطر واحد", "One line"),
            CreatedByUserId: accountant.Id,
            Lines: new[]
            {
                new ManualJournalLineInput(
                    "1200",
                    MoneyEgp.From(100m),
                    MoneyEgp.Zero,
                    "Lonely debit"
                ),
            }
        );

        var act = async () => await handler.HandleAsync(command, CancellationToken.None);

        await act.Should()
            .ThrowAsync<InvalidOperationException>()
            .Where(ex =>
                ex.Message.Contains("at least 2 lines", StringComparison.OrdinalIgnoreCase)
            );
    }

    private static CreateManualAdjustingJournalHandler BuildHandler(AppDbContext db) =>
        new(
            db,
            new TestClock(new DateTime(2026, 5, 8, 11, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore()
        );

    private static async Task<User> SeedUserWithRolesAsync(
        AppDbContext db,
        params string[] roleCodes
    )
    {
        var roles = roleCodes
            .Select(c => new Role(code: c, name: new ArabicEnglishText(c, c), requiresMfa: false))
            .ToList();
        var user = new User(
            email: $"op-{Guid.NewGuid():N}@firm.eg",
            displayName: new ArabicEnglishText("مشغل", "Op"),
            passwordHash: "argon2id$m=65536,t=3,p=4$AAAA$BBBB",
            preferredLanguage: Language.Ar,
            passwordMustChange: false
        );
        foreach (var r in roles)
        {
            user.Roles.Add(r);
            db.Add(r);
        }
        db.Add(user);
        await db.SaveChangesAsync();
        return user;
    }

    private sealed class TestClock(DateTime utcNow) : IClock
    {
        public DateTime UtcNow { get; } = utcNow;
    }

    private sealed class CaptureAuditLogStore : IAuditLogStore
    {
        public List<AuditLogPayload> Captured { get; } = [];

        public Task<AuditLogEntry> AppendAsync(
            AuditLogPayload payload,
            CancellationToken cancellationToken = default
        )
        {
            ArgumentNullException.ThrowIfNull(payload);
            Captured.Add(payload);
            return Task.FromResult(
                new AuditLogEntry(
                    index: Captured.Count,
                    tsUtc: DateTime.UtcNow,
                    actorUserId: payload.ActorUserId,
                    actorFirmName: payload.ActorFirmName,
                    companyId: payload.CompanyId,
                    kind: payload.Kind,
                    payloadJson: payload.PayloadJson,
                    prevHash: new byte[32],
                    thisHash: new byte[32]
                )
            );
        }
    }
}
