using EgyptTax.Application.Audit;
using EgyptTax.Application.Journals;
using EgyptTax.Domain.Audit;
using EgyptTax.Domain.Documents;
using EgyptTax.Domain.Identity;
using EgyptTax.Infrastructure.Journals;
using EgyptTax.Infrastructure.Persistence;
using EgyptTax.IntegrationTests.Infrastructure;
using EgyptTax.SharedKernel;
using EgyptTax.SharedKernel.Time;
using Microsoft.EntityFrameworkCore;

namespace EgyptTax.IntegrationTests.Journals;

/// <summary>
/// T172 / FR-012 — reversal-voucher contract. Closes the loop with
/// T153's PostedDocumentImmutabilityGuard hint: when a non-tax-
/// impacting document needs correction, the operator creates a
/// reversal voucher referencing the original. This test pins the
/// behaviour end-to-end.
///
/// Invariants asserted across the file:
///   * Reversal flips debits ↔ credits per line; amounts are equal
///     so the books wash to zero.
///   * Reversal carries ReversesJournalVoucherId pointing at the
///     original.
///   * Each original may be reversed exactly once (FR-012 single-
///     reversal).
///   * Reversal-of-reversal chains are refused.
///   * Same FR-031 role gate as manual adjustments (Bookkeeper
///     rejected; rejection is auditable).
/// </summary>
[Collection(SqlServerCollection.Name)]
public class ReversalJournalTests(SqlServerFixture fixture)
{
    private readonly SqlServerFixture _fixture = fixture;

    [Fact]
    public async Task ReversalVoucher_FlipsDebitsAndCredits_AndLinksBackToOriginal()
    {
        await using var db = await _fixture.CreateContextAsync();
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");
        var original = await CreateOriginalManualVoucherAsync(db, accountant.Id);

        var handler = new CreateReversalJournalHandler(db,
            new TestClock(new DateTime(2026, 5, 9, 11, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore());

        var reversal = await handler.HandleAsync(new CreateReversalJournalCommand(
            OriginalJournalVoucherId: original.Id,
            ReversalDate: new DateOnly(2026, 5, 9),
            ReversalNarration: new ArabicEnglishText("عكس قيد", "Reverse: incorrect accrual"),
            CreatedByUserId: accountant.Id), CancellationToken.None);

        reversal.ReversesJournalVoucherId.Should().Be(original.Id);
        reversal.IsAutoGenerated.Should().BeFalse();
        reversal.Lines.Should().HaveCount(original.Lines.Count);

        // Per-line flip: each original-debit account is now credited
        // for the same amount, and vice-versa.
        foreach (var origLine in original.Lines)
        {
            var revLine = reversal.Lines.Single(l => l.AccountCode == origLine.AccountCode);
            revLine.Debit.Amount.Should().Be(origLine.Credit.Amount,
                because: $"reversal MUST flip debit↔credit per line; account {origLine.AccountCode}");
            revLine.Credit.Amount.Should().Be(origLine.Debit.Amount);
        }

        // Reversal voucher itself is balanced (and so is the
        // original + reversal pair, which washes to zero).
        reversal.Lines.Sum(l => l.Debit.Amount).Should().Be(reversal.Lines.Sum(l => l.Credit.Amount));

        // Round-trip via EF.
        db.ChangeTracker.Clear();
        var reloaded = await db.Set<JournalVoucher>().AsNoTracking()
            .Include(v => v.Lines)
            .FirstAsync(v => v.Id == reversal.Id);
        reloaded.ReversesJournalVoucherId.Should().Be(original.Id);
        reloaded.Lines.Should().HaveCount(original.Lines.Count);
    }

    [Fact]
    public async Task SecondReversalAttempt_AgainstSameOriginal_IsRefused()
    {
        await using var db = await _fixture.CreateContextAsync();
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");
        var original = await CreateOriginalManualVoucherAsync(db, accountant.Id);

        var handler = new CreateReversalJournalHandler(db,
            new TestClock(new DateTime(2026, 5, 9, 11, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore());

        // First reversal succeeds.
        await handler.HandleAsync(new CreateReversalJournalCommand(
            OriginalJournalVoucherId: original.Id,
            ReversalDate: new DateOnly(2026, 5, 9),
            ReversalNarration: new ArabicEnglishText("عكس", "First reversal"),
            CreatedByUserId: accountant.Id), CancellationToken.None);

        // Second reversal MUST be refused.
        var act = async () => await handler.HandleAsync(new CreateReversalJournalCommand(
            OriginalJournalVoucherId: original.Id,
            ReversalDate: new DateOnly(2026, 5, 10),
            ReversalNarration: new ArabicEnglishText("عكس مكرر", "Second reversal (should fail)"),
            CreatedByUserId: accountant.Id), CancellationToken.None);

        await act.Should().ThrowAsync<InvalidOperationException>()
            .Where(ex => ex.Message.Contains("already been posted", StringComparison.OrdinalIgnoreCase)
                || ex.Message.Contains("already reversed", StringComparison.OrdinalIgnoreCase));

        // Exactly 2 vouchers persisted (original + 1 reversal).
        var totalCount = await db.Set<JournalVoucher>().AsNoTracking().CountAsync();
        totalCount.Should().Be(2,
            because: "FR-012 single-reversal — the second attempt must NOT have produced a third voucher");
    }

    [Fact]
    public async Task ReversalOfReversal_IsRefused_AtAggregateBoundary()
    {
        // Even if the handler's "already reversed" check were bypassed
        // somehow, the aggregate factory ALSO refuses to reverse a
        // voucher that is itself a reversal — defence in depth.
        await using var db = await _fixture.CreateContextAsync();
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");
        var original = await CreateOriginalManualVoucherAsync(db, accountant.Id);

        var firstReversal = JournalVoucher.CreateReversal(
            original: original,
            reversalDate: new DateOnly(2026, 5, 9),
            reversalNarration: new ArabicEnglishText("عكس", "First reversal"),
            createdByUserId: accountant.Id,
            createdAtUtc: DateTime.UtcNow);

        // Try to reverse the reversal directly via the factory.
        var act = () => JournalVoucher.CreateReversal(
            original: firstReversal,
            reversalDate: new DateOnly(2026, 5, 10),
            reversalNarration: new ArabicEnglishText("عكس العكس", "Reversal of reversal"),
            createdByUserId: accountant.Id,
            createdAtUtc: DateTime.UtcNow);

        act.Should().Throw<InvalidOperationException>()
            .WithMessage("*reversal-of-reversal*",
                because: "the aggregate refuses to chain reversals; the operator must post a new manual adjusting voucher instead");
    }

    [Fact]
    public async Task NonExistentOriginal_IsRefused_BeforeRoleCheck()
    {
        await using var db = await _fixture.CreateContextAsync();
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");

        var handler = new CreateReversalJournalHandler(db,
            new TestClock(new DateTime(2026, 5, 9, 11, 0, 0, DateTimeKind.Utc)),
            new CaptureAuditLogStore());

        var act = async () => await handler.HandleAsync(new CreateReversalJournalCommand(
            OriginalJournalVoucherId: Guid.NewGuid(),
            ReversalDate: new DateOnly(2026, 5, 9),
            ReversalNarration: new ArabicEnglishText("عكس", "Reverse a ghost"),
            CreatedByUserId: accountant.Id), CancellationToken.None);

        await act.Should().ThrowAsync<InvalidOperationException>()
            .Where(ex => ex.Message.Contains("not found", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task Bookkeeper_Cannot_CreateReversal_AndRejectionIsAudited()
    {
        await using var db = await _fixture.CreateContextAsync();
        var bookkeeper = await SeedUserWithRolesAsync(db, "Bookkeeper");
        var accountant = await SeedUserWithRolesAsync(db, "Accountant");
        var original = await CreateOriginalManualVoucherAsync(db, accountant.Id);

        var audit = new CaptureAuditLogStore();
        var handler = new CreateReversalJournalHandler(db,
            new TestClock(new DateTime(2026, 5, 9, 11, 0, 0, DateTimeKind.Utc)),
            audit);

        var act = async () => await handler.HandleAsync(new CreateReversalJournalCommand(
            OriginalJournalVoucherId: original.Id,
            ReversalDate: new DateOnly(2026, 5, 9),
            ReversalNarration: new ArabicEnglishText("محاولة", "Bookkeeper attempt"),
            CreatedByUserId: bookkeeper.Id), CancellationToken.None);

        await act.Should().ThrowAsync<UnauthorizedAccessException>()
            .Where(ex => ex.Message.Contains("FR-031", StringComparison.OrdinalIgnoreCase));

        audit.Captured.Should().Contain(p => p.Kind == "journal_voucher.reversal.permission_denied",
            because: "the FR-031 rejection on the reversal path MUST be auditable, same as the manual-adjustment path");

        // No reversal voucher persisted.
        var reversalCount = await db.Set<JournalVoucher>().AsNoTracking()
            .CountAsync(v => v.ReversesJournalVoucherId == original.Id);
        reversalCount.Should().Be(0);
    }

    private static async Task<JournalVoucher> CreateOriginalManualVoucherAsync(AppDbContext db, Guid creatorId)
    {
        var voucher = JournalVoucher.CreateManual(
            date: new DateOnly(2026, 5, 8),
            narration: new ArabicEnglishText("قيد أصلي", "Original manual voucher"),
            createdByUserId: creatorId,
            createdAtUtc: new DateTime(2026, 5, 8, 11, 0, 0, DateTimeKind.Utc),
            lines: new[]
            {
                ("5200", MoneyEgp.From(1000m), MoneyEgp.Zero, "Salaries expense"),
                ("2200", MoneyEgp.Zero, MoneyEgp.From(1000m), "Salaries payable"),
            });
        db.Add(voucher);
        await db.SaveChangesAsync();
        return voucher;
    }

    private static async Task<User> SeedUserWithRolesAsync(AppDbContext db, params string[] roleCodes)
    {
        var roles = roleCodes.Select(c => new Role(
            code: c, name: new ArabicEnglishText(c, c), requiresMfa: false)).ToList();
        var user = new User(
            email: $"op-{Guid.NewGuid():N}@firm.eg",
            displayName: new ArabicEnglishText("مشغل", "Op"),
            passwordHash: "argon2id$m=65536,t=3,p=4$AAAA$BBBB",
            preferredLanguage: Language.Ar,
            passwordMustChange: false);
        foreach (var r in roles) { user.Roles.Add(r); db.Add(r); }
        db.Add(user);
        await db.SaveChangesAsync();
        return user;
    }

    private sealed class TestClock(DateTime utcNow) : IClock
    {
        public DateTime UtcNow { get; } = utcNow;
    }

    private sealed class CaptureAuditLogStore : IAuditLogStore
    {
        public List<AuditLogPayload> Captured { get; } = [];
        public Task<AuditLogEntry> AppendAsync(AuditLogPayload payload, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(payload);
            Captured.Add(payload);
            return Task.FromResult(new AuditLogEntry(
                index: Captured.Count, tsUtc: DateTime.UtcNow,
                actorUserId: payload.ActorUserId, actorFirmName: payload.ActorFirmName,
                companyId: payload.CompanyId, kind: payload.Kind, payloadJson: payload.PayloadJson,
                prevHash: new byte[32], thisHash: new byte[32]));
        }
    }
}
