<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EgyptTax.UnitTests</RootNamespace>
    <AssemblyName>EgyptTax.UnitTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EgyptTax.SharedKernel\EgyptTax.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\EgyptTax.Domain\EgyptTax.Domain.csproj" />
    <ProjectReference Include="..\..\src\EgyptTax.Application\EgyptTax.Application.csproj" />
    <ProjectReference Include="..\..\src\EgyptTax.Infrastructure\EgyptTax.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\EgyptTax.Web\EgyptTax.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>

</Project>
