using EgyptTax.SharedKernel;

namespace EgyptTax.Domain.Tax;

/// <summary>
/// G2 / FR-046 / US7 — quarterly Form 41 (نموذج 41) WHT filing.
/// Each row represents the company's submitted (or in-progress)
/// Form 41 for one (fiscal_year, quarter) pair. Generated by
/// the GenerateForm41 handler from the supplier-payment WHT
/// certificates accrued in the period; transitions to Filed via
/// MarkForm41Filed (one-time per quarter — second mark refused).
/// Once Filed, the included WHT entries are immutable for further
/// inclusion in any other Form 41 (US7 scenario 3, T200).
/// </summary>
public sealed class Form41Filing
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public int FiscalYear { get; init; }
    public int Quarter { get; init; }
    public Form41Status Status { get; private set; } = Form41Status.Unfiled;
    public DateTime GeneratedAtUtc { get; init; }
    public DateTime? FiledAtUtc { get; private set; }
    public Guid? FiledByUserId { get; private set; }
    public string PdfPath { get; private set; } = "";
    public string StructuredJsonPath { get; private set; } = "";
    public MoneyEgp TotalWhtPayable { get; init; } = MoneyEgp.Zero;
    public int LineCount { get; init; }

    private Form41Filing() { }

    private Form41Filing(
        int fiscalYear,
        int quarter,
        DateTime generatedAtUtc,
        string pdfPath,
        string structuredJsonPath,
        MoneyEgp totalWhtPayable,
        int lineCount
    )
    {
        FiscalYear = fiscalYear;
        Quarter = quarter;
        GeneratedAtUtc = generatedAtUtc;
        PdfPath = pdfPath;
        StructuredJsonPath = structuredJsonPath;
        TotalWhtPayable = totalWhtPayable;
        LineCount = lineCount;
    }

    /// <summary>FR-046 / T209 — produced by the GenerateForm41
    /// handler after the payload + PDF have been written to
    /// disk. Status starts Unfiled; a separate handler transitions
    /// to Filed.</summary>
    public static Form41Filing CreateUnfiled(
        int fiscalYear,
        int quarter,
        DateTime generatedAtUtc,
        string pdfPath,
        string structuredJsonPath,
        MoneyEgp totalWhtPayable,
        int lineCount
    )
    {
        if (fiscalYear is < 2000 or > 2099)
        {
            throw new ArgumentOutOfRangeException(
                nameof(fiscalYear),
                $"Fiscal year {fiscalYear} is outside the supported [2000, 2099] range."
            );
        }
        if (quarter is < 1 or > 4)
        {
            throw new ArgumentOutOfRangeException(
                nameof(quarter),
                $"Quarter {quarter} must be 1, 2, 3, or 4."
            );
        }
        if (lineCount < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(lineCount),
                "Line count cannot be negative."
            );
        }
        return new Form41Filing(
            fiscalYear,
            quarter,
            generatedAtUtc,
            pdfPath ?? "",
            structuredJsonPath ?? "",
            totalWhtPayable,
            lineCount
        );
    }

    /// <summary>FR-046 — one-time per quarter. Second call MUST be
    /// refused so an inspector sees a single canonical filing per
    /// (year, quarter). T200 (immutability test) drives off the
    /// transition + an associated lock on the included WHT entries.</summary>
    public void MarkFiled(Guid filedByUserId, DateTime filedAtUtc)
    {
        if (Status == Form41Status.Filed)
        {
            throw new InvalidOperationException(
                $"Form 41 for {FiscalYear}-Q{Quarter} is already Filed at {FiledAtUtc:yyyy-MM-dd HH:mm:ss}; cannot mark it filed twice."
            );
        }
        Status = Form41Status.Filed;
        FiledAtUtc = filedAtUtc;
        FiledByUserId = filedByUserId;
    }
}

/// <summary>FR-046 — lifecycle of a Form 41 filing. `Overdue`
/// is a derived display state (set by the lifecycle dashboard
/// query when an Unfiled filing's regulatory due date has passed)
/// rather than a transition the operator drives.</summary>
public enum Form41Status
{
    Unfiled,
    Filed,
    Overdue,
}
