using EgyptTax.Domain.Workflow;
using EgyptTax.SharedKernel;

namespace EgyptTax.Domain.Documents;

/// <summary>
/// C5 / FR-029 / FR-030 / FR-031 — manually-created journal voucher
/// for the adjusting + reversal flows that don't have an auto-emit
/// path. The post-time auto-emitted journal rows for sales /
/// purchase / expense documents continue to flow through the
/// existing <see cref="EgyptTax.Domain.Accounting.JournalEntry"/>
/// aggregate (kept untouched — US1's plumbing); JournalVoucher is
/// the operator-facing surface for FR-031 manual adjustments and
/// the FR-012 reversal-voucher path the inspection-bundle hint
/// already promises.
///
/// Invariants enforced at the factory:
///   * ≥ 2 lines.
///   * Every line debits XOR credits (non-negative on the chosen
///     side; the other side is zero).
///   * SUM(debit) == SUM(credit) per voucher (FR-030).
///
/// Reversal vouchers carry <see cref="ReversesJournalVoucherId"/>
/// pointing at the original; the <see cref="CreateReversal"/>
/// factory will land in the next batch.
/// </summary>
public sealed class JournalVoucher
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public DateOnly Date { get; init; }
    public DocumentType? SourceDocumentType { get; init; }
    public Guid? SourceDocumentId { get; init; }
    public ArabicEnglishText Narration { get; init; }
    public bool IsAutoGenerated { get; init; }
    public Guid? ReversesJournalVoucherId { get; init; }
    public Guid CreatedByUserId { get; init; }
    public DateTime CreatedAtUtc { get; init; }

    private readonly List<JournalVoucherLine> _lines = new();
    public IReadOnlyCollection<JournalVoucherLine> Lines => _lines;

    private JournalVoucher() { Narration = new ArabicEnglishText("", ""); }

    private JournalVoucher(
        DateOnly date,
        ArabicEnglishText narration,
        Guid createdByUserId,
        DateTime createdAtUtc,
        DocumentType? sourceDocumentType,
        Guid? sourceDocumentId,
        bool isAutoGenerated,
        Guid? reversesJournalVoucherId)
    {
        Date = date;
        Narration = narration;
        CreatedByUserId = createdByUserId;
        CreatedAtUtc = createdAtUtc;
        SourceDocumentType = sourceDocumentType;
        SourceDocumentId = sourceDocumentId;
        IsAutoGenerated = isAutoGenerated;
        ReversesJournalVoucherId = reversesJournalVoucherId;
    }

    /// <summary>
    /// Factory for a manual adjusting voucher (FR-031). Validates
    /// lines + balance invariant before construction; an unbalanced
    /// caller-supplied set never produces a JournalVoucher
    /// instance, so a downstream EF Save can never persist a
    /// broken voucher.
    /// </summary>
    public static JournalVoucher CreateManual(
        DateOnly date,
        ArabicEnglishText narration,
        Guid createdByUserId,
        DateTime createdAtUtc,
        IEnumerable<(string AccountCode, MoneyEgp Debit, MoneyEgp Credit, string Description)> lines)
    {
        ArgumentNullException.ThrowIfNull(lines);
        if (createdByUserId == Guid.Empty)
        {
            throw new ArgumentException("CreatedByUserId is required.", nameof(createdByUserId));
        }

        var voucher = new JournalVoucher(
            date: date,
            narration: narration,
            createdByUserId: createdByUserId,
            createdAtUtc: createdAtUtc,
            sourceDocumentType: null,
            sourceDocumentId: null,
            isAutoGenerated: false,
            reversesJournalVoucherId: null);

        foreach (var l in lines)
        {
            voucher._lines.Add(new JournalVoucherLine(
                voucher.Id, l.AccountCode, l.Debit, l.Credit, l.Description));
        }

        voucher.AssertInvariants();
        return voucher;
    }

    /// <summary>
    /// FR-012 reversal-voucher factory. Builds a balanced JournalVoucher
    /// whose lines are the <paramref name="original"/>'s lines with
    /// debits and credits flipped (a credit becomes a debit of the
    /// same amount and vice versa). The reversal carries
    /// <see cref="ReversesJournalVoucherId"/> = original.Id so the
    /// audit trail + the journal listing surface the back-pointer.
    ///
    /// "Original cannot itself be a reversal" + "original cannot
    /// already have been reversed" are HANDLER-side checks (they
    /// require a DB lookup); the factory itself is pure-domain and
    /// only refuses the cases visible from the original's fields:
    /// the original MUST be persisted (non-zero id) and MUST NOT
    /// itself be a reversal (no reversal-of-reversal chains —
    /// inspectors would never untangle them).
    /// </summary>
    public static JournalVoucher CreateReversal(
        JournalVoucher original,
        DateOnly reversalDate,
        ArabicEnglishText reversalNarration,
        Guid createdByUserId,
        DateTime createdAtUtc)
    {
        ArgumentNullException.ThrowIfNull(original);
        if (createdByUserId == Guid.Empty)
        {
            throw new ArgumentException("CreatedByUserId is required.", nameof(createdByUserId));
        }
        if (original.ReversesJournalVoucherId is not null)
        {
            throw new InvalidOperationException(
                $"Cannot reverse JournalVoucher {original.Id}: it is itself a reversal of {original.ReversesJournalVoucherId}. " +
                "Reversal-of-reversal chains would be impossible for an inspector to untangle; instead, post a new manual adjusting voucher with the desired effect.");
        }

        var reversal = new JournalVoucher(
            date: reversalDate,
            narration: reversalNarration,
            createdByUserId: createdByUserId,
            createdAtUtc: createdAtUtc,
            sourceDocumentType: original.SourceDocumentType,
            sourceDocumentId: original.SourceDocumentId,
            isAutoGenerated: false,
            reversesJournalVoucherId: original.Id);

        // Flip debit ↔ credit per line so the books wash to zero.
        foreach (var l in original._lines)
        {
            reversal._lines.Add(new JournalVoucherLine(
                journalVoucherId: reversal.Id,
                accountCode: l.AccountCode,
                debit: l.Credit,
                credit: l.Debit,
                description: $"Reversal of: {l.Description}"));
        }

        reversal.AssertInvariants();
        return reversal;
    }

    private void AssertInvariants()
    {
        if (_lines.Count < 2)
        {
            throw new InvalidOperationException(
                $"JournalVoucher {Id} requires at least 2 lines (a debit and a credit); got {_lines.Count}.");
        }

        var sumDebits = _lines.Sum(l => l.Debit.Amount);
        var sumCredits = _lines.Sum(l => l.Credit.Amount);
        if (sumDebits != sumCredits)
        {
            throw new InvalidOperationException(
                $"JournalVoucher {Id} is unbalanced: debits {sumDebits:F2} vs credits {sumCredits:F2}. FR-030 requires equality.");
        }
    }
}
