using EgyptTax.Domain.Workflow;
using EgyptTax.SharedKernel;

namespace EgyptTax.Domain.Documents;

/// <summary>
/// C5 / FR-029 / FR-030 / FR-031 — manually-created journal voucher
/// for the adjusting + reversal flows that don't have an auto-emit
/// path. The post-time auto-emitted journal rows for sales /
/// purchase / expense documents continue to flow through the
/// existing <see cref="EgyptTax.Domain.Accounting.JournalEntry"/>
/// aggregate (kept untouched — US1's plumbing); JournalVoucher is
/// the operator-facing surface for FR-031 manual adjustments and
/// the FR-012 reversal-voucher path the inspection-bundle hint
/// already promises.
///
/// Invariants enforced at the factory:
///   * ≥ 2 lines.
///   * Every line debits XOR credits (non-negative on the chosen
///     side; the other side is zero).
///   * SUM(debit) == SUM(credit) per voucher (FR-030).
///
/// Reversal vouchers carry <see cref="ReversesJournalVoucherId"/>
/// pointing at the original; the <see cref="CreateReversal"/>
/// factory will land in the next batch.
/// </summary>
public sealed class JournalVoucher
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public DateOnly Date { get; init; }
    public DocumentType? SourceDocumentType { get; init; }
    public Guid? SourceDocumentId { get; init; }
    public ArabicEnglishText Narration { get; init; }
    public bool IsAutoGenerated { get; init; }
    public Guid? ReversesJournalVoucherId { get; init; }
    public Guid CreatedByUserId { get; init; }
    public DateTime CreatedAtUtc { get; init; }

    private readonly List<JournalVoucherLine> _lines = new();
    public IReadOnlyCollection<JournalVoucherLine> Lines => _lines;

    private JournalVoucher() { Narration = new ArabicEnglishText("", ""); }

    private JournalVoucher(
        DateOnly date,
        ArabicEnglishText narration,
        Guid createdByUserId,
        DateTime createdAtUtc,
        DocumentType? sourceDocumentType,
        Guid? sourceDocumentId,
        bool isAutoGenerated,
        Guid? reversesJournalVoucherId)
    {
        Date = date;
        Narration = narration;
        CreatedByUserId = createdByUserId;
        CreatedAtUtc = createdAtUtc;
        SourceDocumentType = sourceDocumentType;
        SourceDocumentId = sourceDocumentId;
        IsAutoGenerated = isAutoGenerated;
        ReversesJournalVoucherId = reversesJournalVoucherId;
    }

    /// <summary>
    /// Factory for a manual adjusting voucher (FR-031). Validates
    /// lines + balance invariant before construction; an unbalanced
    /// caller-supplied set never produces a JournalVoucher
    /// instance, so a downstream EF Save can never persist a
    /// broken voucher.
    /// </summary>
    public static JournalVoucher CreateManual(
        DateOnly date,
        ArabicEnglishText narration,
        Guid createdByUserId,
        DateTime createdAtUtc,
        IEnumerable<(string AccountCode, MoneyEgp Debit, MoneyEgp Credit, string Description)> lines)
    {
        ArgumentNullException.ThrowIfNull(lines);
        if (createdByUserId == Guid.Empty)
        {
            throw new ArgumentException("CreatedByUserId is required.", nameof(createdByUserId));
        }

        var voucher = new JournalVoucher(
            date: date,
            narration: narration,
            createdByUserId: createdByUserId,
            createdAtUtc: createdAtUtc,
            sourceDocumentType: null,
            sourceDocumentId: null,
            isAutoGenerated: false,
            reversesJournalVoucherId: null);

        foreach (var l in lines)
        {
            voucher._lines.Add(new JournalVoucherLine(
                voucher.Id, l.AccountCode, l.Debit, l.Credit, l.Description));
        }

        voucher.AssertInvariants();
        return voucher;
    }

    private void AssertInvariants()
    {
        if (_lines.Count < 2)
        {
            throw new InvalidOperationException(
                $"JournalVoucher {Id} requires at least 2 lines (a debit and a credit); got {_lines.Count}.");
        }

        var sumDebits = _lines.Sum(l => l.Debit.Amount);
        var sumCredits = _lines.Sum(l => l.Credit.Amount);
        if (sumDebits != sumCredits)
        {
            throw new InvalidOperationException(
                $"JournalVoucher {Id} is unbalanced: debits {sumDebits:F2} vs credits {sumCredits:F2}. FR-030 requires equality.");
        }
    }
}
