using System.Runtime.Versioning;
using System.Security.Cryptography.X509Certificates;
using EgyptTax.Application.Compliance.CertificateMonitor;

namespace EgyptTax.Infrastructure.Compliance.CertificateMonitor;

/// <summary>
/// Reads <c>LocalMachine\My</c> via <c>X509Store</c> and surfaces certs
/// relevant to DaftarX (HTTPS binding + ETA signing). Pure read; no
/// modification of the store. Windows-only by definition (the app
/// itself is Windows-Service-on-prem so this is safe).
/// </summary>
[SupportedOSPlatform("windows")]
public sealed class WindowsCertificateMonitorQuery : ICertificateMonitorQuery
{
    public IReadOnlyList<CertificateInfo> List(DateTime nowUtc)
    {
        var results = new List<CertificateInfo>();

        try
        {
            using var store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
            store.Open(OpenFlags.ReadOnly);
            foreach (var cert in store.Certificates)
            {
                var role = ClassifyRole(cert);
                if (role == CertificateRole.Other)
                {
                    // Only surface DaftarX + ETA signing certs to keep
                    // the dashboard focused. The user doesn't need to
                    // see Microsoft's machine certs here.
                    continue;
                }
                results.Add(BuildInfo(cert, role, nowUtc));
            }
        }
        catch
        {
            // Store may be inaccessible (rare; would need a broken
            // permission set). Surface an empty list — UI explains.
        }

        return results
            .OrderByDescending(c => (int)c.Urgency)  // expired/critical first
            .ThenBy(c => c.NotAfterUtc)              // then nearest expiry
            .ToList();
    }

    private static CertificateRole ClassifyRole(X509Certificate2 cert)
    {
        // DaftarX HTTPS cert generated by setup-https.ps1 has a
        // friendly name of "DaftarX HTTPS Certificate" + Subject
        // includes "O=DaftarX".
        if (cert.FriendlyName.Contains("DaftarX", StringComparison.OrdinalIgnoreCase)
            || cert.Subject.Contains("O=DaftarX", StringComparison.OrdinalIgnoreCase))
        {
            return CertificateRole.DaftarXHttps;
        }

        // ETA signing certs typically come from Egypt Trust / MCDR with
        // subject patterns including "ETA" or the issuer being the
        // Egyptian PKI authority. This is heuristic; real ETA installs
        // can refine via configurable patterns later.
        var subject = cert.Subject;
        var issuer = cert.Issuer;
        if (subject.Contains("ETA", StringComparison.OrdinalIgnoreCase)
            || issuer.Contains("Egypt Trust", StringComparison.OrdinalIgnoreCase)
            || issuer.Contains("MCDR", StringComparison.OrdinalIgnoreCase))
        {
            return CertificateRole.EtaSigning;
        }

        return CertificateRole.Other;
    }

    private static CertificateInfo BuildInfo(X509Certificate2 cert, CertificateRole role, DateTime nowUtc)
    {
        var notAfterUtc = cert.NotAfter.ToUniversalTime();
        var days = (int)Math.Floor((notAfterUtc - nowUtc).TotalDays);
        var urgency = days switch
        {
            < 0   => CertificateUrgency.Expired,
            <= 7  => CertificateUrgency.Critical,
            <= 14 => CertificateUrgency.RenewSoon,
            <= 30 => CertificateUrgency.PlanRenewal,
            _     => CertificateUrgency.Healthy,
        };

        return new CertificateInfo(
            Thumbprint:      cert.Thumbprint,
            Subject:         cert.Subject,
            Issuer:          cert.Issuer,
            NotBeforeUtc:    cert.NotBefore.ToUniversalTime(),
            NotAfterUtc:     notAfterUtc,
            FriendlyName:    string.IsNullOrEmpty(cert.FriendlyName) ? cert.Subject : cert.FriendlyName,
            HasPrivateKey:   cert.HasPrivateKey,
            Role:            role,
            DaysUntilExpiry: days,
            Urgency:         urgency);
    }
}
