<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EgyptTax.SharedKernel</RootNamespace>
    <AssemblyName>EgyptTax.SharedKernel</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Localization\terminology.ar.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Localization\terminology.en.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
